### ISSUE TITLE
Build broken after https://github.com/xbmc/xbmc/pull/9499 merge

### ISSUE THREAD

**Issue by asavah** [mapfau/inputstream.mpd#12]
https://github.com/mapfau/inputstream.mpd/blob/master/src/MainDash.cpp#L631

```
~/src/inputstream.mpd/src/MainDash.cpp: In member function ‘void Session::GetSupportedDecrypterURN(std::pair<std::basic_string<char>, std::basic_string<char> >&)’:
/home/asavah/edgecraft/src/inputstream.mpd/src/MainDash.cpp:631:50: error: no matching function for call to ‘ADDON::CHelper_libXBMC_addon::TranslateSpecialProtocol(char [1024], char [1024], int)’
   xbmc->TranslateSpecialProtocol(path, path, 1024);
                                                  ^
~/src/inputstream.mpd/src/MainDash.cpp:631:50: note: candidate is:
In file included from ~/src/inputstream.mpd/src/MainDash.cpp:27:0:
~/build/rpi3/rootfs/usr/include/kodi/libXBMC_addon.h:345:11: note: char* ADDON::CHelper_libXBMC_addon::TranslateSpecialProtocol(const char*)
     char *TranslateSpecialProtocol(const char *source)
           ^
~/build/rpi3/rootfs/usr/include/kodi/libXBMC_addon.h:345:11: note:   candidate expects 1 argument, 3 provided
CMakeFiles/inputstream.mpd.dir/build.make:62: recipe for target 'CMakeFiles/inputstream.mpd.dir/src/MainDash.cpp.o' failed
```

Note: full path replaced with ~ in output.

**Comment by mapfau** [comment]
Thanks, its known, I cannot compile anything because kodis change to VS2015.
The PR to get the part you mentioned running was merged yesterday evening.

I'll try to fix it without compiler available....

**Comment by asavah** [comment]
No hurries/worries just wanted to let you know that you may have forgotten to change the actual code in the addon after all the suggested changes in the PR, with the "original" PR it was building fine.

**Comment by asavah** [comment]
Thanks.
Builds fine after https://github.com/mapfau/inputstream.mpd/commit/d3265960edab4363c150fd888d345adc1ac7bf96 (cross build gcc 4.9-linaro).
Won't be able to runtime test until night, but *if* it does not work that would be another issue :)

**Comment by mapfau** [comment]
@asavah  it will not work with current decrypter of libdev because of an change in the interface between inputstream.mpd and decrypters. I'm sure decrypter from libdev will be fixed soon.
(libdev=github.com/liberty-developer)
